### ISSUE TITLE
Use TypeScript types during bundling

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-edge-handlers#15]
If the Edge handlers is written in TypeScript and is using our type definitions, should Rollbar throw an error while transpiling TypeScript and there is a type error? At the moment, it does not seem to.

**Comment by shortdiv** [comment]
Good point, we need to create a way of capturing any type errors and propagating it to the user when bundling

**Comment by ehmicky** [comment]
I would expect Rollup to use `tsc` under the hood for transpiling TypeScript, so there might an option to surface `tsc` errors/warnings.

**Comment by ehmicky** [comment]
We have removed the TypeScript transpiling, so this can be closed.
