### ISSUE TITLE
Feat(bundling): generate predictable filenames for bundles

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-plugin-edge-handlers#45]
**Which problem is this feature request solving?**

I'm working https://github.com/netlify/cli/issues/1236 on and need to read both the bundle file and manifest file from the `.netlify/edge-handlers` directory.
The manifest file has a predictable name `manifest.json`, but bundles have a hash as the filename.
Moreover, old bundles are not deleted between build commands and a new bundle is generated even if the code remains the same:
![image](https://user-images.githubusercontent.com/26760571/93315599-e8155280-f813-11ea-8cc6-f085492620cd.png)

To reproduce:
1. Set up a project with an `edge-handlers` directory.
2. Run `netlify build` multiple times (with CLI version `>=v2.63.2`)
3. See that each time a new bundle is created.

**Describe the solution you'd like**

We can keep the current behaviour and also save the latest bundle as `latest` or `bundle`.
Also, not sure why the hash changes if the code remains the same, but that is less of an issue (the main issue here is creating redundant files on users machines).
I believe the code responsible for that is here:
https://github.com/netlify/netlify-plugin-edge-handlers/blob/9657a5aa38b683ac20ac9aeef6868ca16efbaf3a/src/index.js#L37

**Describe alternatives you've considered**

I can look at the creation date of files and use the most recent one.

**Can you submit a pull request?**

Yes, I believe we can update the code here to write bundle with a predictable name:
https://github.com/netlify/netlify-plugin-edge-handlers/blob/9657a5aa38b683ac20ac9aeef6868ca16efbaf3a/src/index.js#L144

**Comment by erezrokah** [comment]
Update, as @ehmicky pointed out, I can read the `manifest.json` file and then use the `sha` property to determine the last bundle.

**Comment by mraerino** [comment]
we can totally think about using a fixed name for handler bundles. i'd like to change that once we're tackling local serving of edge handlers and watching for changes / reloads

**Comment by ehmicky** [comment]
I have added #48, #49 and #50 to track some points mentioned in this issue.

**Comment by ehmicky** [comment]
Done!
