### ISSUE TITLE
Bundles checksum should remain the same when the handler did not change

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-edge-handlers#50]
It seems like the bundle's checksum changes even when the Edge handler source code is not changing.
We should provide with consistent checksums instead, as it might help with caching them at some point in the future.

**Comment by shortdiv** [comment]
Good point, can we generate a hash from the file contents similar to how webpack does it with output files?

**Comment by ehmicky** [comment]
How would this look?

Note: at the moment, we are making a SHA1 digest of the bundle's content.

https://github.com/netlify/netlify-plugin-edge-handlers/blob/a9f8b0b11a1a476876966310a04ecc7acb051701/src/index.js#L127

**Comment by ehmicky** [comment]
Done at #66.
