### ISSUE TITLE
Upgrade minimal Node.js version to Node 12

### ISSUE THREAD

**Issue by lukasholzer** [netlify/netlify-plugin-edge-handlers#660]
This issue originates out of netlify/team-dev#34 (internal link)

We should upgrade the minimal Node.js version to Node >=12.20.0 as the CLI is already dropping the support for Node.js version < 12 https://github.com/netlify/cli/issues/3512.

In the CLI we had some hardcoding to check the edge handler versions are run at least with node 10.

```
 // the edge handlers plugin only works on node >= 10
  const version = Number.parseInt(process.version.slice(1).split('.')[0])
  const EDGE_HANDLER_MIN_VERSION = 10
```

As we are moving forward with this the edge handlers plugin can drop the support and potentially update dependencies that where blocked by this.

**Comment by ehmicky** [comment]
Done in https://github.com/netlify/netlify-plugin-edge-handlers/pull/676
