### ISSUE TITLE
Code minification

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-edge-handlers#73]
Rollup [has an option](https://rollupjs.org/guide/en/#outputcompact) to minify the bundle. Should it be used?

**Comment by shortdiv** [comment]
I like this idea a lot, I think we should minify

**Comment by mraerino** [comment]
+1

**Comment by ehmicky** [comment]
I added the `compact` option in #76. However, all it does is compressing whitespaces. It does not do real minification, such as renaming variables to shorter names, so it does not decrease the bundle size that much.
Should we also add a Rollup plugin to do real minification?

**Comment by ehmicky** [comment]
Done at #79.
