### ISSUE TITLE
This repo needs CODEOWNERS

### ISSUE THREAD

**Issue by mraerino** [netlify/netlify-plugin-edge-handlers#84]
**Which problem is this feature request solving?**

Explicit ownership of the project

**Describe the solution you'd like**

i think this should be owned by the NodeJS speciality and Pod B.
@ehmicky has been putting a lot of work in to maintain it already and it feels like this is pretty isolated from the rest of the larger edge handlers feature.

**Describe alternatives you've considered**

Pod D / Traffic & Delivery (@netlify/delivery) could own this, but we usually don't deal with the build-time and have no specific NodeJS experience.

**Can you submit a pull request?**

Yes

**Comment by shortdiv** [comment]
I like the idea of ownership being on Pod B, since this plugin is a core plugin used in buildbot, we'd want any changes to buildbot or to the cli reflected as soon as possible. So this makes the most sense!
