### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by mraerino** [netlify/netlify-plugin-edge-handlers#89]
**Which problem is this feature request solving?**

Engineers don't know how to release the plugin to npm

**Describe the solution you'd like**

Put instructions into the readme

**Describe alternatives you've considered**

n/a

**Can you submit a pull request?**

No. I don't know how to release.

cc @ehmicky

**Comment by ehmicky** [comment]
I will update this :+1:

**Comment by ehmicky** [comment]
See also https://github.com/netlify/engineering/issues/177

**Comment by erezrokah** [comment]
Done in https://github.com/netlify/netlify-plugin-edge-handlers/pull/110
